### ISSUE TITLE
BAILEYS

### ISSUE THREAD

**Issue by Teamolduser** [adiwajshing/WhatsAppInfoBot#23]
IS END OF WHATSAPP OT ERA ELSE BAILEYS REPO GOT PRIVATE OR DELETE

**Comment by natanjborba** [comment]
UP!

**Comment by kaykyr** [comment]
UP

**Comment by Teamolduser** [comment]
> UP!

What ?

**Comment by Teamolduser** [comment]
> UP

Up what ?

**Comment by WevertonCouto** [comment]
What's happened with the baileys' repository?

**Comment by Teamolduser** [comment]
> What's happened with the baileys' repository?

Maybe got deleted or got private

**Comment by natanjborba** [comment]
The Baileys library is gone, if anyone knows more information let us know.

**Comment by WevertonCouto** [comment]
Does anyone have the contact of the creator?

**Comment by Teamolduser** [comment]
> Does anyone have the contact of the creator?

No if you want a email then you find on profile

**Comment by Teamolduser** [comment]
> Does anyone have the contact of the creator?

Wait for some or some days or some months for updates if did nothing there end of WhatsApp era

**Comment by kaykyr** [comment]
Follow Discord Server for more informations:
https://discord.com/invite/WeJM5FP9GG

NPM still alive:
https://www.npmjs.com/package/@adiwajshing/baileys

**Comment by techwiz37** [comment]
https://github.com/amiruldev20/Baileys

**Comment by Teamolduser** [comment]
> Follow Discord Server for more informations: https://discord.com/invite/WeJM5FP9GG
> 
> NPM still alive: https://www.npmjs.com/package/@adiwajshing/baileys

Got banned 🚫

**Comment by WevertonCouto** [comment]
> > Follow Discord Server for more informations: https://discord.com/invite/WeJM5FP9GG
> > 
> > NPM still alive: https://www.npmjs.com/package/@adiwajshing/baileys
> 
> Got banned 🚫

Got banned in what ?

**Comment by richard892** [comment]
Hello there,

We noticed that the popular "Baileys" GitHub repository has been taken down by its creator. We know that this can be frustrating for those who were using it in their projects.

If you're one of those developers looking for an alternative to Baileys, we'd like to introduce you to our paid service. Our service provides a REST API that can easily be integrated into your project, giving you the functionality you need without having to worry about maintaining the code yourself.

With our service, you can focus on building your application, while we take care of the underlying infrastructure. Our team of experts is available 24/7 to ensure that your projects run smoothly.

We believe that our service can provide you with a reliable and scalable solution for your messaging needs. If you're interested, we'd love to discuss how we can help you get started.
Connect on telegram for Free trial of our Whatsapp Rest API - https://telegram.me/richard_892
Thank you for your time, and we look forward to hearing from you soon.

Best regards,
Richard
